# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: SpeedTest
          command: sudo apt install pip && pip install speedtest-cli && speedtest
      - run:
          name: Neofetch
          command: sudo apt install neofetch && neofetch 
