name: Z-Mirror Bot
on:
  workflow_dispatch:
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: ""
      - name: Downloading the Script
        run: |
          wget -qq  ${{ secrets.ZCONF}}
      - name: Permission
        run: |
           chmod 777 zgit.sh
      - name: Running the Script
        run: |
           sudo bash zgit.sh
